---
version: 2
updates:
  # workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
