name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

permissions: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.26'
          check-latest: true
          cache: false

      - uses: chainguard-dev/actions/goimports@f45211d3e8f9d2676c6b8cdd6a765435e06c819d # v1.6.13

      - name: Build and Test
        run: |
          go build ./...
          go test -v ./... -race
