name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

permissions: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@a0a960b6ef0a72502b0a8eba85b7f3c00c669505 # main
      - run: |
          go build ./...
          go test ./... -race
